language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  include:
    - stage: "Tests"
      script: cargo test
      allow_failures:
        - rust: nightly
      fast_finish: true

    - stage: "Deploy"
      deploy:
        on:
          branch: master
        provider: cargo
        token: $CRATES_TOKEN